

#logging.level.org.mongodb.driver=DEBUG

spring:
  data:
    mongodb:
      uri: mongodb+srv://dipakpawaras19:Dipak_2425@cluster0.lkxuif7.mongodb.net/journaldb?retryWrites=true&w=majority
      database: journaldb
      auto-index-creation: true

server:
  port: 8080
  servlet:
    context-path: /journal
